### PR TITLE
Implement saving for non-translated website resources

### PR DESCRIPTION
**Pull request by jakkarth**
This patch has 2 components. First, when we initially load the page, we detect whether we have a translator for the page or not. Before this patch, untranslated pages had their import button disabled. After the patch, we annotate the tab to indicate we don't have a translator, and leave the button visible.

Second, when the user interacts with the import button, we check to see if no translators were found, and if so we import the website as a simple URL reference, following the bibtex/biblatex standard. This is modelled after the savePdf functionality.

I have tested this locally with translated and non-translated websites. Note that I did change the savePdf function to use the urldate field instead of the accessDate field, in order to match the bibtex standard. JabRef now correctly shows the URL access date on imported PDFs and simple webpages.

### CODE REVIEW

**Comment by tobiasdiez** [comment]
That looks nice, thanks a lot for your work!

One thing that I'm still missing from a ui viewpoint is a clearer indication that there is no proper bibliographic information on that page that the extension recognizes. For example, currently zotero doesn't provide a way to import from arxiv overview pages like https://arxiv.org/a/diez_t_1.html. Thus, with this PR, the jabref button would show also for these pages and users only recognize later in jabref that the information is probably not what they expect. I'm not sure what's the best way to tackle this issue. We should definitely show a different icon (say grayed-out) if there are no translators (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction/setIcon). Is this enough? Or should we show a small confirmation popup when the user clicks the jabref icon on a page without translators? What do you think?

**Comment by jakkarth** [comment]
I'm not sure about the UI concern. I agree that it might be a little confusing, but if I'm collecting a lot of non-translated sources, having to confirm every time that this is the behavior I want, that could be pretty frustrating. On hover, the title text for the button does change based on whether translators are present for the page. Changing the icon too might be a good idea, but greying it out could indicate that it's disabled, when actually it's enabled but without the extra annotations for the source.

Maybe for pages where we do have translators, we could overlay a small green + over the JabRef icon, indicating that there's additional information available via a translator. And the rest of the time, the icon is still in color but without the +. Would that be doable?

**Comment by jakkarth** [comment]
I've added a version of the icon with a green + to indicate that it has extended annotations from a translator. I've included svg and png versions of the modified icon alongside the original, and updated the code in background.js to switch to the appropriate icon as needed.

**Comment by jakkarth** [comment]
@tobiasdiez Anything else I can do to move this forward?

**Comment by jakkarth** [comment]
@tobiasdiez bump

**Comment by jakkarth** [comment]
@tobiasdiez still hoping to get this merged...

**Comment by jakkarth** [comment]
@tobiasdiez @Siedlerchr @siphalor ?

**Comment by Siedlerchr** [comment]
from my point of view lgtm

**Review by Siedlerchr — APPROVED** [review]

**Comment by jakkarth** [comment]
Having been swayed by the discussion [here](https://sfconservancy.org/GiveUpGitHub/), I intend to close my github account shortly. I would very much like this to be merged before that occurs. @tobiasdiez @Siedlerchr @Siedlerchr this MR has been open for almost 3 months. I don't know who else to ping to bring this to the attention of someone capable of merging it. It certainly doesn't encourage participation and contribution to your project when MRs are left ignored for months on end.

**Comment by Siedlerchr** [comment]
Sorry for the delay. I thought someone merged your PR already. I understand the situation, I would be frustrated s well. However,  Please keep in min that we are all working on JabRef in our free time,

**Comment by jakkarth** [comment]
I understand that you all are working on JabRef in your free time, and I've done my best to be respectful of that. But open source software thrives when more developers are engaged, so that more people can be working on it in their free time.

In this instance, you had a user who saw a need, had the technical skill to fill that need, did so voluntarily, and tried to contribute that back to the project as a whole. Had that gone smoothly, I might have become a regular contributor. However, being basically ignored for three months despite repeatedly asking people to merge this has left me frustrated. Other devs, seeking to understand whether this project is active and worth contributing to, will see the problem that played out here and be less likely to contribute themselves. It shouldn't take 3 months and repeated pings to get something this simple merged. That creates a toxic environment that will drive away future contributors. I myself won't be contributing to this project in the future, when it's clear my contributions are not appreciated since they are not merged in a reasonable time.

You suggest that I keep in mind that you're all working on JabRef in your free time. I humbly suggest that you extend that same courtesy to non-core developers. Best of luck with your project.

**Comment by tobiasdiez** [comment]
@jakkarth I'm very sorry for the late reply. I've been away from my main developer machine the last couple of months and have not found the time yet to setup a temporary solution to test this PR. This will sadly also not change until December or so. But once I've moved and settled down, I will test this PR and publish the new version of the extension. Sorry again for the delay. You are right in expecting a better experience, regardless of "open-source" and "working in our leisure time" or similar points.

**Pull request merged**
