### PR TITLE
Fix broken link to jabref.json

### LINKED ISSUE #76: Broken link in README
Link to jabref.json in Mac-OS installation steps is broken.

Wrong URL:  https://github.com/JabRef/jabref/blob/master/buildres/jabref.json

Correct URL: https://github.com/JabRef/jabref/blob/master/buildres/windows/jabref.json

### PR DESCRIPTION
**Pull request by arshadkazmi42**
Fixes #76

### CODE REVIEW

**Comment by tobiasdiez** [comment]
Thanks for the report and the fix. I would guess that it's better to use the Linux version https://github.com/JabRef/jabref/blob/master/buildres/linux/org.jabref.jabref.json on Mac. As I don't have a Mac, I'm not sure how it works and what changes are necessary. In case you are a mac user, it would be great if you could play around a bit and then report what worked for you.

**Comment by arshadkazmi42** [comment]
@tobiasdiez I tried both windows and linux files.
Both does not seems to work.
I am seeing this error 
Screen Shot 2019-10-26 at 2 05 36 PM

**Comment by arshadkazmi42** [comment]
How can I verify if this is working? I tried on wikipedia and can see message till `Send to jabref...`

**Comment by tobiasdiez** [comment]
This error means that Firefox cannot find JabRef, so in other words the path specified in the `org.jabref.jabref.json` file is not correct. You can try to edit this file with the correct path, then everything should work. So after the message "Send to JabRef" is shown, JabRef opens and imports the bibliographic entry.

**Comment by arshadkazmi42** [comment]
@tobiasdiez I downloaded this file https://github.com/JabRef/jabref/blob/master/buildres/linux/jabrefHost.py and used this location as path in my `org.jabref.jabref.json`
Still getting the same issue.
Any thoughts? I am on MacOS

**Comment by tobiasdiez** [comment]
Mhh, strange. That should have worked. Maybe try to put the `py` file somewhere else and/or try to specify the path in `org.jabref.jabref.json` in different ways (e.g. absolute or relative path). You can also try to move the json file to `/Library/Application Support/Mozilla/NativeMessagingHosts/org.jabref.jabref.json` or to `~/Library/Application Support/Mozilla/NativeMessagingHosts/org.jabref.jabref.json`

**Comment by arshadkazmi42** [comment]
I tried moving `py` file in same location as json file. In external path, tried moving the file in both the locations `~/Library` and `/Library`

Still no luck, I tried firefox addon debug option and seeing these logs

Screen Shot 2019-10-27 at 4 19 29 PM


Is there any other way to debug it more?

**Comment by tobiasdiez** [comment]
According to https://stackoverflow.com/a/54187367/873661, there should be more details in Firefox Menu --> Web Developer --> Browser Console

**Comment by tobiasdiez** [comment]
In #75, we just found out that the problem on linux was a missing executable flag. Could you please try to run `chmod +x jabrefHost.py`.

**Comment by arshadkazmi42** [comment]
@tobiasdiez I tried setting permission of `py` file using `chmod +x` still seeing the same error

I did the following,  
- created file `org.jabref.jabref` in `~/Library/Application Support/Mozilla/NativeMessagingHosts`
- create `jabrefHost.py` in `/Users/arshad/Arshad` and used this path inside the above file
- installed the addon in firefox

Am I missing anything in this?

**Comment by tobiasdiez** [comment]
😞 That should have worked. I'm running out of ideas what the problem could be. What is printed in Firefox's Browser console?

**Comment by Siedlerchr** [comment]
@LyzardKing  Any idea?

**Comment by LyzardKing** [comment]
so the json should point to the python file
and the python file should be in the proper location.
I think that should be the "ideal" scenario..
Does that still fail?

**Comment by arshadkazmi42** [comment]
@LyzardKing what do you mean by proper location? Same directory where json file exists?

**Comment by LyzardKing** [comment]
The mac version doesn't include the python script yet! I forgot...
I'd have to look at how it can call the jabref executable..
@arshadkazmi42 You have the .app in the applications dir right?

**Comment by arshadkazmi42** [comment]
Yes. Correct

**Comment by LyzardKing** [comment]
Ok.. so you can open it like a folder, to see where the executable is
Then you'd need to set that path in the python script

**Comment by LyzardKing** [comment]
could you open the python script and try setting JABREF_PATH to `/Applications/JabRef.app/Contents/MacOS/JabRef`

**Comment by arshadkazmi42** [comment]
Updated the python script to  this

`jabrefHost.py`

```
#!/usr/bin/python3 -u

# Note that running python with the `-u` flag is required on Windows,
# in order to ensure that stdin and stdout are opened in binary, rather
# than text, mode.

import json
import sys
import struct
import subprocess
import shlex
import logging
import shutil
from pathlib import Path

# We assume that this python script is located in "jabref/lib" while the executable is "jabref/bin/JabRef"
script_dir = Path(__file__).resolve().parent.parent
JABREF_PATH = script_dir / "/Applications/JabRef.app/Contents/MacOS/JabRef"
if not JABREF_PATH.exists():
    JABREF_PATH = shutil.which("jabref")

logging_dir = Path.home() / ".mozilla/native-messaging-hosts/"
if not logging_dir.exists():
    logging_dir.mkdir(parents=True)
logging.basicConfig(filename=logging_dir / 'jabref_browser_extension.log')

# Read a message from stdin and decode it.
def get_message():
    raw_length = sys.stdin.buffer.read(4)
    if not raw_length:
        logging.error("Raw_length \n")
        sys.exit(0)
    message_length = struct.unpack('=I', raw_length)[0]
    logging.info("Got length: {} bytes to be read\n".format(message_length))
    message = sys.stdin.buffer.read(message_length).decode("utf-8")
    logging.info("Got message of {} chars\n".format(len(message)))
    data = json.loads(message)
    logging.info("Successfully retrieved JSON\n")
    return data


# Encode a message for transmission, given its content.
def encode_message(message_content):
    encoded_content = json.dumps(message_content).encode("utf-8")
    encoded_length = struct.pack('=I', len(encoded_content))
    return {'length': encoded_length, 'content': struct.pack(str(len(encoded_content))+"s",encoded_content)}


# Send an encoded message to stdout.
def send_message(message):
    encoded_message = encode_message(message)
    sys.stdout.buffer.write(encoded_message['length'])
    sys.stdout.buffer.write(encoded_message['content'])
    sys.stdout.buffer.flush()

def add_jabref_entry(data):
    cmd = str(JABREF_PATH) + " -importBibtex " + "\"" + data + "\""
    try:
        response = subprocess.check_output(shlex.split(cmd), stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as exc:
        logging.error("Failed to call JabRef: %s %s", exc.returncode, exc.output)
    else:
        logging.info(f'Called JabRef and got: {response}')
    return response


logging.info("Starting JabRef backend")

try:
    message = get_message()
except Exception as e:
    message = str(e)
logging.info(str(message))

if 'status' in message and message["status"] == "validate":
    cmd = str(JABREF_PATH) + " -version"
    try:
        response = subprocess.check_output(shlex.split(cmd), stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as exc:
        logging.error("Failed to call JabRef: %s %s", exc.returncode, exc.output)
        send_message({"message": "jarNotFound", "path": JABREF_PATH})
    else:
        logging.info(f'{response}')
        send_message({"message": "jarFound"})
else:
    entry = message["text"]
    output = add_jabref_entry(entry)
    send_message({"message": "ok", "output": str(output)})
```

`org.jabref.jabref.json`

```

{
  "name": "org.jabref.jabref",
  "description": "JabRef",
  "path": "jabrefHost.py",
  "type": "stdio",
  "allowed_extensions": [
    "@jabfox"
  ]
}
```

Above is the two file with updated code. both the files are kept at `~/Library/Application Support/Mozilla/NativeMessagingHosts`

Am I doing anything wrong here?

**Comment by LyzardKing** [comment]
and the line in the python script has to be changed to this:
JABREF_PATH = "/Applications/JabRef.app/Contents/MacOS/JabRef"

**Comment by arshadkazmi42** [comment]
Updated the path and reinstalled the addon. Still seeing the same error

**Comment by LyzardKing** [comment]
just to be sure, if you call that path in a terminal jabref starts, right?

**Comment by arshadkazmi42** [comment]
Yes it starts

**Comment by arshadkazmi42** [comment]
For checking this I am going to this page https://en.wikipedia.org/wiki/Hacker
and clicking on Jafref icon. Is that fine?

**Comment by LyzardKing** [comment]
Ok, so the path is correct.. and the json has the full path, not just `jabrefHost.py`?

**Comment by arshadkazmi42** [comment]
JSON has only the py filename in path `jabrefHost.py`.
Just now tried adding abosulte path 

```
{
  "name": "org.jabref.jabref",
  "description": "JabRef",
  "path": "/var/root/Library/Application Support/Mozilla/NativeMessagingHosts/jabrefHost.py",
  "type": "stdio",
  "allowed_extensions": [
    "@jabfox"
  ]
}
```

still no luck

**Comment by LyzardKing** [comment]
try moving the python script somwhere else...it might be that location(plus the path correction)
Thy your home directory for example..
In the future it'll live in the .app

**Comment by arshadkazmi42** [comment]
moved file to /Users/user_name/name/jabrefHost.py

still seeing same error

**Comment by LyzardKing** [comment]
...I'm out of ideas for now ;)
without the right computer it's hard to debug...
If you open the extension settings what error does it show?

**Comment by arshadkazmi42** [comment]
i am seeing this error

https://github.com/JabRef/JabFox/pull/77#issuecomment-546582929

If you can guide me on how and where can i start with debugging may be i can look into it

**Comment by LyzardKing** [comment]
If you start the python script in a terminal does it start? (it doesn't show anything, but waits on the stdio buffer)

**Comment by LyzardKing** [comment]
You can stop it with a Ctrl-C, since it's not really doing anything. But if it starts at all it's a good thing.

**Comment by tobiasdiez** [comment]
The disconnected port message is only shown if the python script is not found by Firefox. If the python script does not find JabRef then a different error message would be shown. However, I have no idea how to find out the reason why Firefox does not find the python script (or is not able to run it).

**Comment by arshadkazmi42** [comment]
@LyzardKing So I tried running the python script using python3. I am seeing this error

```
Traceback (most recent call last):
  File "/Users/arshad/Arshad/jabrefHost.py", line 19, in <module>
    if not JABREF_PATH.exists():
AttributeError: 'str' object has no attribute 'exists'
```

**Comment by LyzardKing** [comment]
Because it's a Path object instead.
Change the usual line to
JABREF_PATH = Path( "/Applications/JabRef.app/Contents/MacOS/JabRef")

**Comment by arshadkazmi42** [comment]
Updated the path, now python script is working, 
Its not giving any error and does not displays anything in the terminal

**Comment by arshadkazmi42** [comment]
> The disconnected port message is only shown if the python script is not found by Firefox. If the python script does not find JabRef then a different error message would be shown. However, I have no idea how to find out the reason why Firefox does not find the python script (or is not able to run it).

json file is at this location `Library/Application Support/Mozilla/NativeMessagingHosts/org.jabref.jabref.jso`

Firefox will read it from there right? or it needs to be somewhere else or something needs to be configured for this?

**Comment by tobiasdiez** [comment]
That seems correct. Are there any errors in the Firefox Menu --> Web Developer --> Browser console?

**Comment by arshadkazmi42** [comment]
> That seems correct. Are there any errors in the Firefox Menu --> Web Developer --> Browser console?

Yes.

```
Unix error 13 during operation open on file /Library/Application Support/Mozilla/NativeMessagingHosts/org.jabref.jabref.json (Permission denied)
```

This is the error I am getting. Looks like it can't open the json file itself

**Comment by LyzardKing** [comment]
Do you have two copies of the json file, one in ~/.. and another one in /Library/..?

**Comment by arshadkazmi42** [comment]
@LyzardKing Yes. I do. in `/Library/...`  with this name `jabref.json`

**Comment by LyzardKing** [comment]
try removing that and keeop only the one in ~/..

**Comment by arshadkazmi42** [comment]
Seeing this error now `No such native application org.jabref.jabref`

**Comment by tobiasdiez** [comment]
Just to make sure, please try the following:
- delete all files in both `~/Library...` and in `/Library` (make a backup of the json file)
- put json file into `/Library/...` with name `org.jabref.jabref.json`
- try to run addon
- in case there is an error, delete json in `/Library` and put one into `~/Library/...` again with the name `org.jabref.jabref.json`

Thanks for your consistent help in this endeavour!

**Comment by arshadkazmi42** [comment]
I tried above steps.
On moving the json file to `/Library/...`
I have started getting some other error `Failed to execute command "/Users/...../jabrefHost.py"`

Now its reading the json file, but can't execute `jabrefHost.py` I tried giving `chmod +x jabrefHost.py` still same error

**Comment by LyzardKing** [comment]
By same error do you mean the `Failed to execute command`?

**Comment by arshadkazmi42** [comment]
> By same error do you mean the `Failed to execute command`?

Yes.

**Comment by arshadkazmi42** [comment]
Yes. I tried moving the `py` file to same location with json.
On that I got these in Browser console
```
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 640
FBO Texture Target: TEXTURE_2D
OpenGL compositor Initialized Succesfully.
Version: 2.1 INTEL-10.36.19
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics 640
FBO Texture Target: TEXTURE_2D
navigator.requestMediaKeySystemAccess promise rejected 0x80530009 'Key system is unsupported'
MediaKeySystemAccess::GetKeySystemStatus(com.widevine.alpha) result=available msg=''
```

**Comment by LyzardKing** [comment]
That seems to be an error regarding the DRM implementation (widevine)..
Nothing jabref related..

**Comment by arshadkazmi42** [comment]
Anything else we can try to validate this?

**Comment by tobiasdiez** [comment]
Sorry, I've no idea why this is not working...I think the above error is also not helpful as it's not JabRef related (and probably not even related to the native messaging stuff). 😢

**Comment by tobiasdiez** [comment]
@arshadkazmi42 Could you solved the issue in the meantime? Maybe it's working now with the new JabRef 5.0 release?

**Comment by arshadkazmi42** [comment]
@tobiasdiez I will look into it ASAP. I will try it with the latest version of JabRef 5.0

**Comment by tobiasdiez** [comment]
@arshadkazmi42 Did you had any luck fixing this? In the meantime, we had some improvements by @LyzardKing concerning the linux scripts, so this might work now?!

**Comment by arshadkazmi42** [comment]
@tobiasdiez havent got a chance to look into this in sometime. will try to have a look at it

**Comment by tobiasdiez** [comment]
Since there has been no progress in some time, I'll close this PR for now. Please feel free to resolve the conflicts after you tested the latest versions!

**Pull request closed without merging**
