### PR TITLE
Chromium install script

### PR DESCRIPTION
**Pull request by LyzardKing**
@tobiasdiez 
This edits the manual install file to add a (terminal) ui, a selection of browsers, and automates the download process.
It depends on https://github.com/JabRef/jabref/pull/5571 on the main repo, which adds the chromium json file

### CODE REVIEW

**Comment by LyzardKing** [comment]
The script itself is a modified version of the keepassxc script, which is GPLv2+
So we should probably add the license header for the script...
Is that an issue?

**Comment by tobiasdiez** [comment]
Mhhh, I removed the install script because I thought it is now obsolete. Normally, the json files are copied correctly using the deb package. Thus, I don't think there is a need for a semi-automated script. Do I miss a use case?

**Comment by LyzardKing** [comment]
I noticed now that you removed the script.
It can be used for the snap/flatpak, to avoid having to add special permissions,
or to add support for other browsers, depending on how many you want to include in the deb.
But if you think it's unnecessary it can be removed..
Do we need to add something extra for rpm?

**Comment by tobiasdiez** [comment]
Ok, then we keep it. Can you please add the license header (if the amount of copied code is relatively large) and readd the script to ignored files in the webext config. Thanks

**Pull request merged**
